<a href="https://colab.research.google.com/github/lekshmi29-lx/DSA_workB7/blob/main/Numpy_pandas_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

1. Create a NumPy array with values from 10 to 49 (inclusive).

● Reshape it into a 4x10 matrix.
● Then extract the last column from the reshaped matrix

In [2]:
import numpy as np

arr = np.arange(10,50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
arr1 = np.reshape(arr,(4,10))
print(arr1)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [4]:
arr1[:,[-1]]

array([[19],
       [29],
       [39],
       [49]])

2. Create two 3×3 matrices:

One filled with all 5s , One with values from 1 to 9
● Add the two matrices
● Multiply them element-wise
● Then find the transpose of the result

In [5]:
m1 = np.full((3,3),5)
print(f"M1:{m1}")
m2 = np.arange(1,10).reshape(3,3)
print(f"M2:{m2}")

M1:[[5 5 5]
 [5 5 5]
 [5 5 5]]
M2:[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
add_matrix = m1 + m2
print("Result: ",add_matrix)

Result:  [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [7]:
transpose_m1 = m1.T
transpose_m2 = m2.T
print('Transpose of M1:',transpose_m1)
print('Transpose of M2:',transpose_m2)

Transpose of M1: [[5 5 5]
 [5 5 5]
 [5 5 5]]
Transpose of M2: [[1 4 7]
 [2 5 8]
 [3 6 9]]


3. Create a NumPy array of 15 random integers between 10 and 100.

● Replace all values greater than 50 with -1
● Count how many values were replaced.

In [8]:
arr2 = np.random.randint(10,101,size=15)
print(arr2)

[78 61 98 62 41 16 79 17 11 83 24 47 97 14 75]


In [9]:
count = np.sum(arr2>50)
print("Count greater than 50: ",count)


Count greater than 50:  8


In [10]:
arr2[arr2>50]=-1
print(arr2)

[-1 -1 -1 -1 41 16 -1 17 11 -1 24 47 -1 14 -1]


4. Generate a 5×4 array with random values between 0 and 1 (float).

● Find the row with the maximum sum of values.
● Normalize each row using the formula: Xnormalized = x-min/max-min

In [11]:
arr3 = np.random.rand(5,4)
print(arr3)

[[0.87045047 0.91955282 0.62492358 0.90045781]
 [0.33820216 0.6571633  0.23474366 0.77661644]
 [0.72700857 0.05794976 0.67533753 0.31794648]
 [0.1820448  0.05751102 0.13217596 0.26704796]
 [0.18535565 0.71706739 0.3594243  0.80949614]]


In [12]:
sum_row = arr3.sum(axis=1)
print("Row sums:",sum_row)
max_sum = np.argmax(sum_row)
#print(max_sum)
print(f"row with the maximum sum of values:{arr3[max_sum]}")

Row sums: [3.31538468 2.00672556 1.77824233 0.63877974 2.07134347]
row with the maximum sum of values:[0.87045047 0.91955282 0.62492358 0.90045781]


In [13]:
min = arr3.min(axis=1).reshape(-1, 1)
max = arr3.max(axis=1).reshape(-1, 1)

normalized_arr = (arr3 - min) / (max - min)
print("Normalized Array:", normalized_arr)

Normalized Array: [[0.83334192 1.         0.         0.9351897 ]
 [0.19092766 0.77955501 0.         1.        ]
 [1.         0.         0.92277056 0.3886007 ]
 [0.5943285  0.         0.35633307 1.        ]
 [0.         0.85191034 0.27889337 1.        ]]


5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

● Find all unique elements
● Find the duplicates (elements that appear more than once)

In [14]:
arr4 = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_value = np.unique(arr4)
print("Unique elements:", unique_value)

Unique elements: [1 3 5 7 9]


In [15]:
count_dup = np.bincount(arr4)
duplicates = np.where(count_dup > 1)[0]
print("Duplicates:", duplicates)

Duplicates: [1 3 5]


6. Create a 6×6 NumPy array with values from 1 to 36.

● Extract the middle 4×4 submatrix.
● Then extract all even numbers from this submatrix.

In [18]:
arr5 = np.arange(1,37).reshape(6,6)
arr5

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [22]:
sub_matrix = arr5[1:5,1:5]
sub_matrix

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [23]:
sub_matrix[sub_matrix % 2 == 0]

array([ 8, 10, 14, 16, 20, 22, 26, 28])

7. Generate an array of shape (3, 4) with values from 0 to 11.

● Reshape it to (2, 6)
● Then flatten it into a 1D array
● Convert the 1D array back to shape (4, 3)

In [24]:
arr6 = np.arange(0,12).reshape(3,4)
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
reshape_arr6 = arr6.reshape(2,6)
print("Reshape into (2,6):",reshape_arr6)

Reshape into (2,6): [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [30]:
flattened = reshape_arr6.flatten()
print("Flatten into 1D: ",flattened)

Flatten into 1D:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [32]:
reshape_flatten = flattened.reshape(4,3)
print(reshape_flatten)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


8 . Create an array: a = np.array([[1, 2], [3, 4]])

● Append a new row [5, 6]
● Then append a new column [7, 8, 9]

In [49]:
arr7 = np.array([[1, 2], [3, 4]])
arr7

array([[1, 2],
       [3, 4]])

In [50]:
arr_row = np.vstack([arr7, [5, 6]])
print(arr_row)

[[1 2]
 [3 4]
 [5 6]]


In [52]:
arr_col = np.column_stack([arr_row,[7,8,9]])
print(arr_col)

[[1 2 7]
 [3 4 8]
 [5 6 9]]


9.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

● Join them into a single array
● Reshape the result into a 3×3 matrix
● Extract the diagonal elements

In [54]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
arr8 = np.concatenate((a,b,c))
print(arr8)

[1 2 3 4 5 6 7 8 9]


In [56]:
arr8_reshape = arr8.reshape(3,3)
print(arr8_reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
arr8_dia = np.diag(arr8_reshape)
print(arr8_dia)

[1 5 9]


10. Create a NumPy array of integers from 1 to 20.

● Extract all values that are divisible by 3 or 5.
● Count how many such values exist.

In [58]:
arr9 = np.arange(1,21)
print(arr9)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [59]:
div_arr = arr9[(arr9 % 5 == 0) | (arr9 % 3 == 0)]
print(div_arr)

[ 3  5  6  9 10 12 15 18 20]


In [61]:
print("Count of Values Divisible by 3 or 5:",div_arr.size)

Count of Values Divisible by 3 or 5: 9


**PANDAS**

In [62]:
import pandas as pd

1. Load the Titanic dataset and display the first 10 rows.

In [63]:
import seaborn as sns
data = sns.load_dataset("titanic")

In [64]:
data.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

2. Find the number of missing values in each column

In [65]:
data.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

3. Find the percentage of passengers who survived, grouped by gender.

In [67]:
data.groupby('sex')['survived'].mean()*100

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

4. Find the average, median, and standard deviation of passenger ages.

In [71]:
age = data['age'].dropna()
age.mean()

np.float64(29.69911764705882)

In [72]:
age.median()

28.0

In [73]:
age.std()

14.526497332334044

5. Count how many passengers were in each class (pclass).

In [74]:
count_pclass = data['pclass'].value_counts()
print(count_pclass)

pclass
3    491
1    216
2    184
Name: count, dtype: int64


6. Show all passengers who were female, under age 18, and survived

In [78]:
data[(data['sex']=='female')&(data['age']<18)&(data['survived']==1)]
#print(show_passenger)

survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  female  16.00      0      0    7.7500        Q   Third   
233         1       3  female   5.00      4      2   31.3875        S   Third   
237         1       2  female   8.00      0      2   26.2500        S  Second   
307         1       1  female  17.00      1      0  108.9000        C   First   
329         1       1  female  16.00      0      1   57.9792        C   First   
381         1       3  female   1.00      0      2   15.7417        C   Third   
389         1       2  female  17.00      0      0   12.0000        C  Second   
435         1       1  female  14.00      1      2  120.0000        S   First   
446         1       2  female  13.00      0      1   19.5000        S  Second   
448         1       3  female   5.00      2      1   19.2583        C   Third   
469         1       3  female   0.75      2      1   19.2583        C   Third   
479         1       3  female   2.00      0      1   12.2875        S   Third   
504         1       1  female  16.00      0      0   86.5000        S   First   
530         1       2  female   2.00      1      1   26.0000        S  Second   
535         1       2  female   7.00      0      2   26.2500        S  Second   
618         1       2  female   4.00      2      1   39.0000        S  Second   
644         1       3  female   0.75      2      1   19.2583        C   Third   
689         1       1  female  15.00      0      1  211.3375        S   First   
691         1       3  female   4.00      0      1   13.4167        C   Third   
720         1       2  female   6.00      0      1   33.0000        S  Second   
750         1       2  female   4.00      1      1   23.0000        S  Second   
777         1       3  female   5.00      0      0   12.4750        S   Third   
780         1       3  female  13.00      0      0    7.2292        C   Third   
781         1       1  female  17.00      1      0   57.0000        S   First   
830         1       3  female  15.00      1      0   14.4542        C   Third   
853         1       1  female  16.00      0      1   39.4000        S   First   
875         1       3  female  15.00      0      0    7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
22   child       False  NaN   Queenstown   yes   True  
39   child       False  NaN    Cherbourg   yes  False  
43   child       False  NaN    Cherbourg   yes  False  
58   child       False  NaN  Southampton   yes  False  
68   woman       False  NaN  Southampton   yes  False  
84   woman       False  NaN  Southampton   yes   True  
156  woman       False  NaN   Queenstown   yes   True  
172  child       False  NaN  Southampton   yes  False  
184  child       False  NaN  Southampton   yes  False  
208  woman       False  NaN   Queenstown   yes   True  
233  child       False  NaN  Southampton   yes  False  
237  child       False  NaN  Southampton   yes  False  
307  

7. Replace missing age values with the median age.

In [85]:
median_age = data['age'].median()
#print(median_age)
data1 = data['age'].fillna(median_age)
print(data1)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64


8. Create a column age_group with values:

a. 'Child' for age < 18
b. 'Adult' for age 18–60
c. 'Senior' for age > 60
d. Use: apply() or np.where() or custom function

In [89]:
data["age_group"] = np.where(data["age"] < 18, "Child",
                        np.where(data["age"] <= 60, "Adult", "Senior"))

print(data[["age", "age_group"]].head(20))

     age age_group
0   22.0     Adult
1   38.0     Adult
2   26.0     Adult
3   35.0     Adult
4   35.0     Adult
5   28.0     Adult
6   54.0     Adult
7    2.0     Child
8   27.0     Adult
9   14.0     Child
10   4.0     Child
11  58.0     Adult
12  20.0     Adult
13  39.0     Adult
14  14.0     Child
15  55.0     Adult
16   2.0     Child
17  28.0     Adult
18  31.0     Adult
19  28.0     Adult


9.  Display the top 5 passengers who paid the highest fare.

In [90]:
data.sort_values(by='fare',ascending=False).head(5)

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
679         1       1    male  36.0      0      1  512.3292        C  First   
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
88          1       1  female  23.0      3      2  263.0000        S  First   
438         0       1    male  64.0      1      4  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone age_group  
679    man        True    B    Cherbourg   yes  False     Adult  
258  woman       False  NaN    Cherbourg   yes   True     Adult  
737    man        True    B    Cherbourg   yes   True     Adult  
88   woman       False    C  Southampton   yes  False     Adult  
438    man        True    C  Southampton    no  False    Senior

10. Find the average fare paid, grouped by both pclass and sex.

In [91]:
data.groupby(['pclass','sex'])['fare'].mean()

pclass  sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64

11. Rename the following columns:

a. 'sex' → 'gender'
b. 'fare' → 'ticket_fare'

In [113]:
data_new = data.rename(columns={
    "sex":"gender",
    "fare":"ticket_fare"
})
data_new

survived  pclass  gender   age  sibsp  parch  ticket_fare embarked  \
0           0       3    male  22.0      1      0       7.2500        S   
1           1       1  female  38.0      1      0      71.2833        C   
2           1       3  female  26.0      0      0       7.9250        S   
3           1       1  female  35.0      1      0      53.1000        S   
4           0       3    male  35.0      0      0       8.0500        S   
..        ...     ...     ...   ...    ...    ...          ...      ...   
886         0       2    male  27.0      0      0      13.0000        S   
887         1       1  female  19.0      0      0      30.0000        S   
888         0       3  female  28.0      1      2      23.4500        S   
889         1       1    male  26.0      0      0      30.0000        C   
890         0       3    male  32.0      0      0       7.7500        Q   

      class    who  adult_male deck  embark_town alive  alone age_group  
0     Third    man        True  NaN  Southampton    no  False     Adult  
1     First  woman       False    C    Cherbourg   yes  False     Adult  
2     Third  woman       False  NaN  Southampton   yes   True     Adult  
3     First  woman       False    C  Southampton   yes  False     Adult  
4     Third    man        True  NaN  Southampton    no   True     Adult  
..      ...    ...         ...  ...          ...   ...    ...       ...  
886  Second    man        True  NaN  Southampton    no   True     Adult  
887   First  woman       False    B  Southampton   yes   True     Adult  
888   Third  woman       False  NaN  Southampton    no  False     Adult  
889   First    man        True    C    Cherbourg   yes   True     Adult  
890   Third    man        True  NaN   Queenstown    no   True     Adult  

[891 rows x 16 columns]

12. Count the number of passengers who survived and didn’t survive, grouped by class.

In [114]:
count_by_class = data.groupby(['pclass', 'survived']).size()
print(count_by_class)

pclass  survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
dtype: int64


13. Find the average age of passengers grouped by both class and gender.

In [116]:
data_new.groupby(['pclass','gender'])['age'].mean()

pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: age, dtype: float64